config/routes.rb
Rails.application.routes.draw do
  # root 'rooms#index'
  mount ActionCable.server => '/cable'
  get 'friends/index'
  get 'friends/edit'
  get 'friends/show'
  resources :students
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :rooms do
    resources :messages
  end
  # resources :users
  get "add_friend" => "students#add_friend"
  get "delete_request", to: "students#delete_request"
  get 'my_request', to: "students#my_request"
  get 'accepted_request', to: "students#accepted_request"
  get 'friend_list', to: 'friends#friend_list'
  get 'message', to: "friends#messages"
  devise_for :users, controllers: {sessions: "users/sessions", :registrations => "users/registrations", :passwords => "users/passwords"}
  get "index", to: "homes#index"
  get 'sign_in' => "homes#sign_in"
  get 'sign_up' => "homes#sign_up"
  get 'forgot_password'=> "homes#forgot_password"
  get 'home_modal' => "homes#home_modal"
  # get '/reset_password/id/edit', to: "users#reset_password"
  get 'reset_password', to: "users#reset_password"
  post '/reset_password', to: 'users#password_update'
   get '/reset_password', to: "users#reset_password"
   patch '/users/:id', to: 'users#password_update'
  # devise_for :admin_users, ActiveAdmin::Devise.config  
  resources :events
  resources :planners
  root "events#index"
  resources :venues 
  resources :address
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @users = User.where.not(id: current_user.id)
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end
  def add_friend
  @frinds = Friend.create(sender_id: params[:sender_id], receiver_id: params[:receiver_id])
  redirect_to students_url 
  end

  def delete_request
    @friend = Friend.where(sender_id: params[:sender_id], receiver_id: params[:receiver_id]).first
    @friend.destroy if @friend.present?
    if params[:cancel_request]
      redirect_to my_request_path
    else
     redirect_to students_path
    end
  end

  def accepted_request
    @frind = Friend.where(sender_id: params[:sender_id], receiver_id: params[:receiver_id]).last
    @frind.update(is_accept: true)
    # room = params[:sender_id] + params[:receiver_id]
    @room = Room.create(sender_id: params[:sender_id], receiver_id: params[:receiver_id])
    redirect_to students_path
   end

  def my_request
    @receive = current_user.receive_requests
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:first_name, :last_name, :city, :description, :test)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :test, style: "display: block" %>
    <%= form.check_box :test %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>First name:</strong>
    <%= student.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= student.last_name %>
  </p>

  <p>
    <strong>City:</strong>
    <%= student.city %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= student.description %>
  </p>

  <p>
    <strong>Test:</strong>
    <%= student.test %>
  </p>
  

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>
<table id="myTable" >
  <tr class="header">    
    <th>First_name</th>
    <th>Last_Name</th>    
    <th>email</th>
    <th colspan="3">Action</th>
  </tr>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>   
        <td><%= user.email %></td>
        <td>
          <% if Friend.where(receiver_id: user.id, sender_id: current_user.id).present? %>
            <%= link_to "Remove", delete_request_path(sender_id: current_user.id, receiver_id: user.id),class: "btn btn-outline-danger" %>
          <% else %>
            <%= link_to "Send request", add_friend_path(sender_id: current_user.id, receiver_id: user.id),class: "btn btn-outline-success " %>
           <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<style>
* {
  box-sizing: border-box;
}
#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 70%;
  border-radius: 10px;
  font-size: 16px;
  padding: 12px 20px 8px 40px;
  border: 1px solid #ddd;
  margin-bottom: 14px;
}

#myTable {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
  font-size: 16px;
}

#myTable th, #myTable td {
  text-align: left;
  padding: 5px;
}

#myTable tr {
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  background-color: #f1f1f1;
}
</style>

app/views/students/my_request.html.erb
	<p id="notice"><%= notice %></p>
<table id="myTable">
	<thead>
		<tr class="header">			
			<th>First name</th>
			<th>Last name</th>
			<th colspan="3">action</th>			
		</tr>
	</thead>
	<tbody>
	  <% @receive.each do |rec_request| %>
		  <% if rec_request.is_accept != true %>	
			  <tr>
					<td><%= rec_request&.sender&.first_name %></td>
					<td><%= rec_request&.sender&.last_name %></td>
					<td><%= link_to "Delete request", delete_request_path(receiver_id: current_user.id, sender_id: rec_request.sender.id, cancel_request: true),class: "btn btn-outline-danger" %></td>
					<td>
						<% if rec_request.is_accept %>
						 <a href="#" class="btn btn-outline-success " >Friend</a>
						<% else %>
						 <%= link_to "Accepted_request", accepted_request_path(receiver_id: current_user.id, sender_id: rec_request.sender.id) ,class: "btn btn-outline-success"%>
						<% end %>
					</td>
			  </tr>
			<% end %>
	  <% end %>
	</tbody>
</table>
<style>
* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 70%;
  border-radius: 10px;
  font-size: 16px;
  padding: 12px 20px 8px 40px;
  border: 1px solid #ddd;
  margin-bottom: 14px;
}

#myTable {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
  font-size: 18px;
}

#myTable th, #myTable td {
  text-align: left;
  padding: 7px;
}

#myTable tr {
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  background-color: #f1f1f1;
}
</style>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>