config/routes.rb
Rails.application.routes.draw do
  # root 'rooms#index'
  mount ActionCable.server => '/cable'
  get 'friends/index'
  get 'friends/edit'
  get 'friends/show'
  resources :students
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :rooms do
    resources :messages
  end
  # resources :users
  get "add_friend" => "students#add_friend"
  get "delete_request", to: "students#delete_request"
  get 'my_request', to: "students#my_request"
  get 'accepted_request', to: "students#accepted_request"
  get 'friend_list', to: 'friends#friend_list'
  get 'message', to: "friends#messages"
  devise_for :users, controllers: {sessions: "users/sessions", :registrations => "users/registrations", :passwords => "users/passwords"}
  get "index", to: "homes#index"
  get 'sign_in' => "homes#sign_in"
  get 'sign_up' => "homes#sign_up"
  get 'forgot_password'=> "homes#forgot_password"
  get 'home_modal' => "homes#home_modal"
  # get '/reset_password/id/edit', to: "users#reset_password"
  get 'reset_password', to: "users#reset_password"
  post '/reset_password', to: 'users#password_update'
   get '/reset_password', to: "users#reset_password"
   patch '/users/:id', to: 'users#password_update'
  # devise_for :admin_users, ActiveAdmin::Devise.config  
  resources :events
  resources :planners
  root "events#index"
  resources :venues 
  resources :address
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :sender, :foreign_key => "sender_id", :class_name => "User" 
	belongs_to :receiver, :foreign_key => "sender_id", :class_name => "User" 
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
  end

  def edit
  end

  def show
  end
  
  def friend_list
    @friends = current_user.receive_requests.where(is_accept: true)
  end

  def messages
    room = params[:sender_id] + params[:receiver_id]
    @friend = User.find_by_id(params[:receiver_id])
    @single_room = Room.find_by_name(room)
    if !@single_room.present?
      @single_room = Room.create(sender_id: params[:sender_id], receiver_id: params[:receiver_id], name: room)
    end
    if @single_room.present?
      redirect_to "/rooms/#{@single_room.id}"
    end
    # @friends = current_user.friends
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/edit.html.erb
<h1>Friends#edit</h1>
<p>Find me in app/views/friends/edit.html.erb</p>

app/views/friends/friend_list.html.erb
<p style="color: green"><%= notice %></p>

<table id="myTable" >
  <tr class="header">    
    <th>First_name</th>
    <th>Last_Name</th>
    <th>email</th>
    <th></th>
  </tr>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.sender.first_name %></td> 
        <td><%= friend.sender.last_name %></td>       
        <td><%= friend.sender.email %></td> 
         <td><%= link_to "Send Message", message_path(sender_id: current_user.id, receiver_id: friend.id),class: "btn btn-outline-danger" %> </td>      
      </tr>
    <% end %>
  </tbody>
</table>


<style>
* {
  box-sizing: border-box;
}
#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 70%;
  border-radius: 10px;
  font-size: 16px;
  padding: 12px 20px 8px 40px;
  border: 1px solid #ddd;
  margin-bottom: 14px;
}

#myTable {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
  font-size: 16px;
}

#myTable th, #myTable td {
  text-align: left;
  padding: 5px;
}

#myTable tr {
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  background-color: #f1f1f1;
}
</style>

app/views/friends/index.html.erb
<h1>Friends#index</h1>
<p>Find me in app/views/friends/index.html.erb</p>

app/views/friends/messages.html.erb
<div class="col-md-10 bg-dark text-light">
  <% if @single_room %>
    <h4 class="text-center"> <%= @single_room.name %> </h4>
  <% end %>
</div>

app/views/friends/show.html.erb
<h1>Friends#show</h1>
<p>Find me in app/views/friends/show.html.erb</p>