config/routes.rb
Rails.application.routes.draw do
  # root 'rooms#index'
  mount ActionCable.server => '/cable'
  get 'friends/index'
  get 'friends/edit'
  get 'friends/show'
  resources :students
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :rooms do
    resources :messages
  end
  # resources :users
  get "add_friend" => "students#add_friend"
  get "delete_request", to: "students#delete_request"
  get 'my_request', to: "students#my_request"
  get 'accepted_request', to: "students#accepted_request"
  get 'friend_list', to: 'friends#friend_list'
  get 'message', to: "friends#messages"
  devise_for :users, controllers: {sessions: "users/sessions", :registrations => "users/registrations", :passwords => "users/passwords"}
  get "index", to: "homes#index"
  get 'sign_in' => "homes#sign_in"
  get 'sign_up' => "homes#sign_up"
  get 'forgot_password'=> "homes#forgot_password"
  get 'home_modal' => "homes#home_modal"
  # get '/reset_password/id/edit', to: "users#reset_password"
  get 'reset_password', to: "users#reset_password"
  post '/reset_password', to: 'users#password_update'
   get '/reset_password', to: "users#reset_password"
   patch '/users/:id', to: 'users#password_update'
  # devise_for :admin_users, ActiveAdmin::Devise.config  
  resources :events
  resources :planners
  root "events#index"
  resources :venues 
  resources :address
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :addressable, polymorphic: true
	validates :city, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
 has_many :planner, dependent: :destroy
 has_many :venues, dependent: :destroy
 accepts_nested_attributes_for :venues, :allow_destroy => true
 accepts_nested_attributes_for :planner, :allow_destroy => true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :sender, :foreign_key => "sender_id", :class_name => "User" 
	belongs_to :receiver, :foreign_key => "sender_id", :class_name => "User" 
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room 
  after_create_commit { broadcast_append_to self.room }
end

app/models/planner.rb
class Planner < ApplicationRecord
 belongs_to :event
 has_many :addresses, dependent: :destroy, :as => :addressable
 accepts_nested_attributes_for :addresses, :allow_destroy => true
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  after_create_commit {broadcast_append_to "rooms"}
  has_many :messages
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :send_requests, :foreign_key => "sender_id", :class_name => "Friend" , dependent: :destroy
  has_many :receive_requests, :foreign_key => "receiver_id", :class_name => "Friend", dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates_uniqueness_of :username, allow_nil: true
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
  has_many :messages
end

app/models/venue.rb
class Venue < ApplicationRecord
	belongs_to :event
	has_one :address, dependent: :destroy, :as => :addressable
	accepts_nested_attributes_for :address, :allow_destroy => true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: %i[ show edit update destroy ]
  # GET /events or /events.json
  def index
    @events = Event.all
     @event = Event.new
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    # @event.build_venue
    1.times { @event.venues.build }
    1.times { @event.planner.build }
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :description, planner_attributes: [:id, :name, :_destroy, addresses_attributes:[:id, :city, :address1, :_destroy]],venues_attributes: [:id, :name, :_destroy,addresses_attributes:[:id, :city, :address1, :_destroy]])
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
  end

  def edit
  end

  def show
  end
  
  def friend_list
    @friends = current_user.receive_requests.where(is_accept: true)
  end

  def messages
    room = params[:sender_id] + params[:receiver_id]
    @friend = User.find_by_id(params[:receiver_id])
    @single_room = Room.find_by_name(room)
    if !@single_room.present?
      @single_room = Room.create(sender_id: params[:sender_id], receiver_id: params[:receiver_id], name: room)
    end
    if @single_room.present?
      redirect_to "/rooms/#{@single_room.id}"
    end
    # @friends = current_user.friends
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		# @homes = Home.all
	end
	def home_modal
		@user = User.new
	end
	def sign_in
	  @user = User.new
	  respond_to do |format|    
      format.js {}
  	end
  end
   def sign_up
   	@user = User.new
	  respond_to do |format|    
      format.js {}
    end
  end
  
  def forgot_password
  	@user = User.new
  	respond_to do |format|    
      format.js {}
    end
  end  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @current_user = current_user
    redirect_to '/signin' unless @current_user
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
    
  end

  def show
    @current_user = current_user
    @single_room = Room.find(params[:id])
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
    @message = Message.new
    render "index"
  end

  def create
    @room = Room.create(name: params["room"]["name"])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def reset_password
    @user = User.find_by_id(params[:id])
  end

  def password_update
    @user = User.find_by_id(params[:user])
    if (params[:password] == params[:password_confirmation])
      @user.update(password: params[:password], password_confirmation: params[:password_confirmation])
      
      redirect_to "/" 
    else
      @error = "password not match"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
    when 'notice' then "alert alert-info"
    when 'success' then "alert alert-success"
    when 'error' then "alert alert-danger"
    when 'alert' then "alert alert-success"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/homes/_form.html.erb
<div class="modal fade" id="exampleModalLong2" tabindex="-1" role="dialog" aria-labelledby="eModalLongTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>        
      </div>
      
      <div class="modal-body">
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <%= link_to "Sign in", sign_in_path, remote: true, role: "tab", class: "btn btn-light nav-item nav-link active", id: "SignIn" %>
          <%= link_to "Sign up", sign_up_path, remote: true, id: "nav-contact-tab", role: "tab", class: "nav-item nav-link" %>
          <%= link_to "Forgot your password?", forgot_password_path, remote: true, id: "forgot-password", class: "nav-item nav-link" %>
        </div>
		    <div class="tab-content" id="nav-tabContent">  
          <div id= "sing-in-container">
             <%= render :partial =>  "devise/sessions/form", user: @user %>
          </div>
           <div id="sing-up-container"></div>
           <div id="forword_modal" ></div>  
		    </div>
      </div>
      <div class="modal-footer">      
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>      
      </div>
    </div>
  </div>
</div>
<script>
  $('#SignIn').click(function(){
    var sign_link = document.getElementById('SignIn');
    var sign_up_link = document.getElementById('nav-contact-tab');
    var fogot_link = document.getElementById('forgot-password');
    sign_link.setAttribute('class', 'btn btn-light nav-item nav-link active');
    sign_up_link.setAttribute('class', 'nav-item nav-link');
    fogot_link.setAttribute('class', 'nav-item nav-link');

  });
  $('#nav-contact-tab').click(function(){
    var sign_link = document.getElementById('SignIn');
    var sign_up_link = document.getElementById('nav-contact-tab');
    var fogot_link = document.getElementById('forgot-password');
    sign_link.setAttribute('class', 'nav-item nav-link');
    fogot_link.setAttribute('class', 'nav-item nav-link');
    sign_up_link.setAttribute('class', 'btn btn-light nav-item nav-link active');
  });
  $('#forgot-password').click(function(){
    var sign_link = document.getElementById('SignIn');
    var sign_up_link = document.getElementById('nav-contact-tab');
    var fogot_link = document.getElementById('forgot-password');
    sign_link.setAttribute('class', 'nav-item nav-link');
    sign_up_link.setAttribute('class', 'nav-item nav-link');
    fogot_link.setAttribute('class', 'btn btn-light nav-item nav-link active');
  });
</script>

app/views/homes/forgot_password.js.erb
$("#forword_modal").html("<%= escape_javascript(render "devise/passwords/form", locals: { resource: @user}) %>");
$("#forword_modal").show();
$("#sing-in-container").hide();
$("#sing-up-container").hide();

app/views/homes/home_modal.js.erb
$('#remote-container').html("<%= escape_javascript render 'homes/form' %>");	
$('#exampleModalLong2').modal('show');
// $('#nav-profile-tab').click();

app/views/homes/sign_in.js.erb
$("#sing-in-container").html("<%= escape_javascript(render "devise/sessions/form", locals: { resource: @user}) %>");
$("#sing-in-container").show();
$("#sing-up-container").hide();
$("#forword_modal").hide();

app/views/homes/sign_up.js.erb
$("#sing-up-container").html("<%= escape_javascript(render "devise/registrations/form", locals: { resource: @user}) %>");
$("#sing-in-container").hide();
$("#sing-up-container").show();
$("#forword_modal").hide();